### ISSUE TITLE
APYPIE module is missing

### ISSUE THREAD

**Issue by tdosek** [nstrug/sync-satellite-org#13]
We need to install APYPIE in order to progress further:

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'apypie'
fatal: [rhte-satellite.oldstable.me.uk -> localhost]: FAILED! => {"changed": false, "msg": "The apypie Python module is required"}

**Comment by tdosek** [comment]
[ec2-user@rhte-satellite ~]$ env python
Python 2.7.5 (default, Jun 11 2019, 14:33:56) 
sudo -i yum install python27-python-pip-8.1.2-3.el7.noarch
sudo scl enable python27 bash
pip install apypie

**Comment by pcfe** [comment]
try this if on Fedora
```bash
pip3 install --user apypie
```

**Comment by tdosek** [comment]
Closing with README.md changes pushed.
